# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconnect.proto\x12\x11\x63reate_connection\"\x10\n\x0e\x43onnectRequest\"\x11\n\x0f\x43onnectResponse2n\n\x14\x43onnectToBoatService\x12V\n\rConnectToBoat\x12!.create_connection.ConnectRequest\x1a\".create_connection.ConnectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTREQUEST']._serialized_start=36
  _globals['_CONNECTREQUEST']._serialized_end=52
  _globals['_CONNECTRESPONSE']._serialized_start=54
  _globals['_CONNECTRESPONSE']._serialized_end=71
  _globals['_CONNECTTOBOATSERVICE']._serialized_start=73
  _globals['_CONNECTTOBOATSERVICE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
