# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connect_pb2 as connect__pb2


class ConnectToBoatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectToBoat = channel.unary_unary(
                '/create_connection.ConnectToBoatService/ConnectToBoat',
                request_serializer=connect__pb2.ConnectRequest.SerializeToString,
                response_deserializer=connect__pb2.ConnectResponse.FromString,
                )


class ConnectToBoatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectToBoat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectToBoatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectToBoat': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToBoat,
                    request_deserializer=connect__pb2.ConnectRequest.FromString,
                    response_serializer=connect__pb2.ConnectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'create_connection.ConnectToBoatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectToBoatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectToBoat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/create_connection.ConnectToBoatService/ConnectToBoat',
            connect__pb2.ConnectRequest.SerializeToString,
            connect__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
