# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import connect_pb2 as connect__pb2


class ConnectToBoatServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConnectToBoat = channel.unary_unary(
        '/create_connection.ConnectToBoatService/ConnectToBoat',
        request_serializer=connect__pb2.ConnectRequest.SerializeToString,
        response_deserializer=connect__pb2.ConnectResponse.FromString,
        )


class ConnectToBoatServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ConnectToBoat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConnectToBoatServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConnectToBoat': grpc.unary_unary_rpc_method_handler(
          servicer.ConnectToBoat,
          request_deserializer=connect__pb2.ConnectRequest.FromString,
          response_serializer=connect__pb2.ConnectResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'create_connection.ConnectToBoatService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
