# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_restart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_restart.proto',
  package='node_restart',
  syntax='proto3',
  serialized_pb=_b('\n\x12node_restart.proto\x12\x0cnode_restart\"\'\n\x12RestartNodeRequest\x12\x11\n\tnode_name\x18\x01 \x01(\t\"&\n\x13RestartNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32h\n\x12RestartNodeService\x12R\n\x0bRestartNode\x12 .node_restart.RestartNodeRequest\x1a!.node_restart.RestartNodeResponseb\x06proto3')
)




_RESTARTNODEREQUEST = _descriptor.Descriptor(
  name='RestartNodeRequest',
  full_name='node_restart.RestartNodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_name', full_name='node_restart.RestartNodeRequest.node_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=75,
)


_RESTARTNODERESPONSE = _descriptor.Descriptor(
  name='RestartNodeResponse',
  full_name='node_restart.RestartNodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='node_restart.RestartNodeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['RestartNodeRequest'] = _RESTARTNODEREQUEST
DESCRIPTOR.message_types_by_name['RestartNodeResponse'] = _RESTARTNODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RestartNodeRequest = _reflection.GeneratedProtocolMessageType('RestartNodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESTARTNODEREQUEST,
  __module__ = 'node_restart_pb2'
  # @@protoc_insertion_point(class_scope:node_restart.RestartNodeRequest)
  ))
_sym_db.RegisterMessage(RestartNodeRequest)

RestartNodeResponse = _reflection.GeneratedProtocolMessageType('RestartNodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESTARTNODERESPONSE,
  __module__ = 'node_restart_pb2'
  # @@protoc_insertion_point(class_scope:node_restart.RestartNodeResponse)
  ))
_sym_db.RegisterMessage(RestartNodeResponse)



_RESTARTNODESERVICE = _descriptor.ServiceDescriptor(
  name='RestartNodeService',
  full_name='node_restart.RestartNodeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=117,
  serialized_end=221,
  methods=[
  _descriptor.MethodDescriptor(
    name='RestartNode',
    full_name='node_restart.RestartNodeService.RestartNode',
    index=0,
    containing_service=None,
    input_type=_RESTARTNODEREQUEST,
    output_type=_RESTARTNODERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTARTNODESERVICE)

DESCRIPTOR.services_by_name['RestartNodeService'] = _RESTARTNODESERVICE

# @@protoc_insertion_point(module_scope)
