# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"L\n\nVideoFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"#\n\x0cVideoRequest\x12\x13\n\x0bvideoSource\x18\x01 \x01(\t2H\n\rVideoStreamer\x12\x37\n\x0bStreamVideo\x12\x13.video.VideoRequest\x1a\x11.video.VideoFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOFRAME']._serialized_start=22
  _globals['_VIDEOFRAME']._serialized_end=98
  _globals['_VIDEOREQUEST']._serialized_start=100
  _globals['_VIDEOREQUEST']._serialized_end=135
  _globals['_VIDEOSTREAMER']._serialized_start=137
  _globals['_VIDEOSTREAMER']._serialized_end=209
# @@protoc_insertion_point(module_scope)
